kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azuredisk-premium-retain
  namespace: dev
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete   # Retain or Delete
volumeBindingMode: WaitForFirstConsumer   # WaitForFirstConsumer or Immediate
allowVolumeExpansion: true    # true or false
parameters:
  storageaccounttype: Standard_LRS   # Premium or Standard
  kind: Managed  
